- import_tasks: yum_install_packages.yaml
  when:
    - OS_DISTRIBUTION == 'centos7'
- import_tasks: create_users_dir.yaml
  when:
    - OS_DISTRIBUTION == 'centos7'
- import_tasks: exec_groupadd.yaml
  when:
    - OS_DISTRIBUTION == 'centos7'
- import_tasks: exec_sefcontext.yaml
  when:
    - OS_DISTRIBUTION == 'centos7'
- import_tasks: deploy_sssd_conf.yaml
  when:
    - OS_DISTRIBUTION == 'centos7'
- import_tasks: edit_sssd_conf.yaml
  when:
    - OS_DISTRIBUTION == 'centos7'
- import_tasks: exec_authconfig.yaml
  when:
    - OS_DISTRIBUTION == 'centos7'
- import_tasks: systemctl_enable_and_restart.yaml
  when:
    - OS_DISTRIBUTION == 'centos7'
